name: Test trigger
# Test, build, and publish a release and tag it with "version-latest" on pushes to master

on:
  workflow_dispatch
  
jobs:
  build:
    name: Test trigger
    runs-on: ubuntu-latest

    steps:
    - name: trigger meta action
      run: |
        curl -sS -o meta.log \
          -X POST https://api.github.com/repos/magellan2/magellan2.github.io/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: token ${{ secrets.META_REPO_ACCESS }}' \
          --data '{
            "event_type": "actions-release-trigger",
            "client_payload": {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "caller_repository" : "${{ github.repository }}",
              "meta_repository" : "${{ github.repository_owner }}/magellan2.github.io",
              "tag" : "v2.1-test",
              "version" : "v2.1.0-100.test",
              "type": "test",
              "action": "test" }}'
        if [ -s meta.log ]; then
          cat meta.log
          rm meta.log
          exit -1
        else
          echo "meta action apparently successful"
          rm meta.log
        fi
